apiVersion: v1
kind: Service
metadata:
  name: studio-timer-service
spec:
  type: NodePort
  selector:
    app: studio-timer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000